name: Pulumi Infra Setup

on:
  push:
    branches:
      - main
    paths:
      - 'infra/**'

jobs:
  setup_infra:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install pulumi pulumi-aws

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Pulumi login
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
        run: pulumi login

      - name: Pulumi stack select
        run: pulumi stack select dev-p --cwd infra

      - name: Pulumi refresh
        run: pulumi refresh --yes --cwd infra

      - name: Pulumi up
        run: pulumi up --yes --cwd infra

      - name: Get Pulumi outputs
        run: pulumi stack output --json --cwd infra > outputs.json

      - name: Extract bucket name from Pulumi outputs
        id: get_bucket_name
        run: echo "::set-output name=bucket_name::$(jq -r .bucket_name outputs.json)"

      - name: Export Pulumi outputs to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1
          S3_BUCKET_NAME: ${{ steps.get_bucket_name.outputs.bucket_name }}
          S3_FILE_NAME: pulumi-outputs.json
        run: |
          aws s3 cp outputs.json s3://$S3_BUCKET_NAME/$S3_FILE_NAME

      - name: Clean up outputs.json
        run: rm outputs.json

      - name: Set output for S3 bucket name
        id: set_s3_output
        run: echo "bucket_name=${{ steps.get_bucket_name.outputs.bucket_name }}" >> $GITHUB_ENV
